
language: php

services:
  - postgresql

directories:
  - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

before_script:
  - psql -c 'create database sistemaacademico_test;' -U postgres
  - composer install --prefer-dist
  - php artisan --env=travis migrate

env:
  - APP_ENV=travis

script: phpunit

notifications:
  email:
    - munizeverton@gmail.com

addons:
  code_climate:
    repo_token: d940a9fc258f0d8358d907593f910137e96f19d65553632beacd35ecbda59f1a