# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

services:
  - postgresql

# list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.1
  # aliased to a recent hhvm version
  - hhvm

before_script:
  - psql -c 'create database sistemaacademico_test;' -U postgres
  - composer install
  - php artisan --env=testing migrate
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    - munizeverton@gmail.com