
language: php

services:
  - postgresql

php:
  - 7.1
  - 7.2

before_script:
  - psql -c 'create database sistemaacademico_test;' -U postgres
  - composer install
  - php artisan --env=travis migrate

env:
  - APP_ENV=travis

script: phpunit

notifications:
  email:
    - munizeverton@gmail.com